# Generated by Django 4.1 on 2023-01-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='item_details',
            field=models.TextField(default='There are no details currently. Sorry!', verbose_name='details'),
        ),
    ]
