# Generated by Django 4.1 on 2023-04-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioitem_item_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='item_git_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
