# Generated by Django 4.1 on 2023-04-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioitem_item_git_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='item_summary',
            field=models.TextField(default='There is no summary currently. Sorry!', verbose_name='summary'),
        ),
    ]
